version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: docflow
      POSTGRES_USER: docflow
      POSTGRES_PASSWORD: ${DB_PASSWORD:-docflow_password_change_me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    build: ./server
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://docflow:${DB_PASSWORD:-docflow_password_change_me}@db:5432/docflow
      SESSION_SECRET: ${SESSION_SECRET:-change_me_to_strong_secret}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      ADMIN_FULL_NAME: ${ADMIN_FULL_NAME:-Admin}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}
      PORT: 8080
      # Опционально для платежей
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID:-}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY:-}
      PAY_RETURN_URL: ${PAY_RETURN_URL:-https://your-domain.com}
      # Опционально для уведомлений
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL:-}
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./server/uploads:/app/uploads

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
